// =========================================================================
// Las frases del formulario de reserva, en los dos idiomas
//
// Viven aqui y no dentro de cada pagina porque el formulario sale en dos
// sitios: en el home (seccion "Haz tu reserva") y en /reserva, que es la
// pagina suelta para mandarle el enlace a un cliente. Escritas una sola vez
// no se pueden descuadrar.
//
// Las dos paginas lo mezclan en su propio TEXTOS con ...TEXTOS_RESERVA.es
// =========================================================================
const TEXTOS_RESERVA = {
    es: {
        resTitulo: "Haz tu reserva",
        resTexto: "La sala completa para tu grupo. Elige el día, cuánto tiempo y listo.",
        resCampoFecha: "Día",
        resCampoHoras: "Duración",
        resCampoHora: "¿A qué hora empiezan?",
        resCampoNombre: "Nombre y apellido",
        resCampoTelefono: "Número de WhatsApp",
        resPagoTitulo: "Pago móvil · abona el 50%",
        resBanco: "Banco:",
        resCedula: "C.I.:",
        resTelefonoPago: "Teléfono:",
        resCampoComprobante: "Comprobante del abono",
        resSubir: "Toca para subir la captura del pago",
        resBtnEnviar: "Enviar reserva",
        resGraciasTitulo: "¡Reserva registrada!",
        resGraciasTexto: "Vamos a confirmar el pago y te escribimos por WhatsApp. Nos vemos pronto.",
        resElegirDia: "Elige un día para ver las horas libres.",
        resSinHoras: "No disponible. Intenta con otra fecha y hora.",
        resSinSitio: "Ese día ya no caben {n} horas.",
        resVerDe: "Ver las de {n} horas",
        resCargando: "Buscando horas libres...",
        resHoraPl: "horas",
        resResumenEntran: "Llegan a las",
        resResumenCantan: "Cantan de",
        resResumenSalen: "Salen antes de",
        resResumenCortesia: "El tiempo empieza a correr 20 minutos después de llegar, para que se instalen con calma. Al final les damos otros 20 para recoger. Nada de eso se cobra.",
        resResumenTotal: "Total",
        resResumenAbono: "Abonas ahora (50%)",
        resResumenResto: "El resto se paga el mismo día.",
        resTasaNota: "Tasa del BCV de hoy",
        resPagoNota: "Haz el pago móvil por el monto del abono y sube la captura aquí abajo. Sin el comprobante no se puede apartar la hora.",
        resComprobanteListo: "Comprobante listo:",
        resErrNombre: "Escribe tu nombre y apellido.",
        resErrTelefono: "Escribe un teléfono válido.",
        resErrComprobante: "Falta subir el comprobante del pago.",
        resErrArchivo: "El archivo tiene que ser una imagen o un PDF.",
        resErrPesado: "Ese archivo pesa demasiado. Prueba con otro.",
        resErrEnvio: "No se pudo enviar. Revisa tu internet e inténtalo de nuevo.",
        resEnviando: "Enviando...",
        resSubiendo: "Subiendo comprobante..."
    },
    en: {
        resTitulo: "Book your night",
        resTexto: "The whole room, just for your group. Pick the day, how long, and you are set.",
        resCampoFecha: "Day",
        resCampoHoras: "Length",
        resCampoHora: "What time do you start?",
        resCampoNombre: "Full name",
        resCampoTelefono: "WhatsApp number",
        resPagoTitulo: "Mobile payment · pay 50% now",
        resBanco: "Bank:",
        resCedula: "ID:",
        resTelefonoPago: "Phone:",
        resCampoComprobante: "Payment receipt",
        resSubir: "Tap to upload your payment screenshot",
        resBtnEnviar: "Send booking",
        resGraciasTitulo: "Booking received!",
        resGraciasTexto: "We will confirm the payment and message you on WhatsApp. See you soon.",
        resElegirDia: "Pick a day to see the free slots.",
        resSinHoras: "Not available. Try another date and time.",
        resSinSitio: "No room for {n} hours that day.",
        resVerDe: "See the {n}-hour slots",
        resCargando: "Looking for free slots...",
        resHoraPl: "hours",
        resResumenEntran: "You arrive at",
        resResumenCantan: "Singing from",
        resResumenSalen: "Out before",
        resResumenCortesia: "The clock starts 20 minutes after you arrive, so you can settle in. At the end you get another 20 to pack up. None of it is charged.",
        resResumenTotal: "Total",
        resResumenAbono: "You pay now (50%)",
        resResumenResto: "The rest is paid on the day.",
        resTasaNota: "Today's BCV rate",
        resPagoNota: "Send the mobile payment for the deposit amount and upload the screenshot below. Without the receipt the slot cannot be held.",
        resComprobanteListo: "Receipt ready:",
        resErrNombre: "Please write your full name.",
        resErrTelefono: "Please write a valid phone number.",
        resErrComprobante: "The payment receipt is missing.",
        resErrArchivo: "The file needs to be an image or a PDF.",
        resErrPesado: "That file is too heavy. Try another one.",
        resErrEnvio: "Could not send it. Check your connection and try again.",
        resEnviando: "Sending...",
        resSubiendo: "Uploading receipt..."
    }
};
